apiVersion: v1
kind: Service
metadata:
  name: wine-model-app
spec:
  selector:
    app: wine-model-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort